spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.5.124:8848
    alicloud:
      access-key: LTAI4G3XjtHbVeXCtGKfMfB2
      secret-key: 1TU7ZaGAysQYEvmmJuvtEoqMqd0x68
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gh-mall

  application:
    name: gh-third-party

server:
  port: 9086
