spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.5.124:8848
  application:
    name: gh-auth-server
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 9088

